---
output: github_document
resource_files:
  bib/mapspamc.bib
bibliography: bib/mapspamc.bib

---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/README-",
  out.width = "100%"
)
```

# mapspamc_mwi

This repository contains the scripts to create crop distribution maps with the [`mapspamc`](https://github.com/michielvandijk/mapspamc) R package for Malawi, covering the year 2010. To run the scripts, the user needs to install `mapspamc` and download the [mapspamc database](https://doi.org/10.5281/zenodo.7031917), which includes all the required input data, including subnational crop statistics for Malawi as well as global maps. Note that the (subnational) statistics were modified for illustrative purposes and therefore results might differ from those presented in SPAM2010 [@Yu2020]. Please use the original SPAM database when presenting crop distribution maps for Malawi.

Detailed information on how to install the package and run the Ethiopia case-study is provided in the articles of the `mapspamc` [package website](https://michielvandijk.github.io/mapspamc/).

<!-- Additional information is available in a scientific journal article [@VanDijk2022b]. Please cite this article if you use the `mapspamc`package. -->

Note that it takes up to several hours to run the models, in particular when a resolution of 30 arc seconds is selected. The table below presents the model dimensions and model running time using a machine with an Intel(R) Xeon(R) E-2276M CPU \@ 2.81 GHz processor and 32 GB RAM.

|                                              | Cross-entropy        | Fitness score        |
|-----------------------------------|------------------|------------------|
| Resolution                                   | 5 arc minutes        | 30 arc seconds       |
| Solve level                                  | 0                    | 0                    |
| Number of crops                              | 29                   | 29                   |
| Number of production systems x crops         | 66                   | 66                   |
| Number of administrative units               | 3 (ADM1), 27 (ADM2)  | 3 (ADM1), 27 (ADM2)  |
| Number of crops with subnational information | 19                   | 19                   |
| Number of cropland cells                     | 1,104                | 104,965              |
| Running time                                 | 271 sec              | 5,610 sec            |
| Solver                                       | IPOPT                | CPLEX                |

## References
